FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app

# install dotnet watch
RUN dotnet tool install -g dotnet-watch
ENV PATH="$PATH:/root/.dotnet/tools"

# Copy .csproj files
COPY ["FurnitureGardenDesign.Data.Common/FurnitureGardenDesign.Data.Common.csproj", "FurnitureGardenDesign.Data.Common/"]
COPY ["FurnitureGardenDesign.Data.Models/FurnitureGardenDesign.Data.Models.csproj", "FurnitureGardenDesign.Data.Models/"]
COPY ["FurnitureGardenDesign.Data/FurnitureGardenDesign.Data.csproj", "FurnitureGardenDesign.Data/"]
COPY ["FurnitureGardenDesign.Services.Automapping/FurnitureGardenDesign.Services.Automapping.csproj", "FurnitureGardenDesign.Services.Automapping/"]
COPY ["FurnitureGardenDesign.Services.Common/FurnitureGardenDesign.Services.Common.csproj", "FurnitureGardenDesign.Services.Common/"]
COPY ["FurnitureGardenDesign.Services.Core/FurnitureGardenDesign.Services.Core.csproj", "FurnitureGardenDesign.Services.Core/"]
COPY ["FurnitureGardenDesign.Web.Infrastructure/FurnitureGardenDesign.Web.Infrastructure.csproj", "FurnitureGardenDesign.Web.Infrastructure/"]
COPY ["FurnitureGardenDesign.Web/FurnitureGardenDesign.Web.csproj", "FurnitureGardenDesign.Web/"]
COPY ["FurnitureGardenDesign.WebApi/FurnitureGardenDesign.WebApi.csproj", "FurnitureGardenDesign.WebApi/"]

RUN dotnet restore "FurnitureGardenDesign.Web/FurnitureGardenDesign.Web.csproj"

EXPOSE 8080
CMD ["dotnet", "watch", "run", "--project", "FurnitureGardenDesign.Web/FurnitureGardenDesign.Web.csproj", "--no-launch-profile"]