<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.3.12" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SendGrid" Version="9.29.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FurnitureGardenDesign.Data.Models\FurnitureGardenDesign.Data.Models.csproj" />
    <ProjectReference Include="..\FurnitureGardenDesign.Data\FurnitureGardenDesign.Data.csproj" />
    <ProjectReference Include="..\FurnitureGardenDesign.Services.Automapping\FurnitureGardenDesign.Services.Automapping.csproj" />
    <ProjectReference Include="..\FurnitureGardenDesign.Services.Common\FurnitureGardenDesign.Services.Common.csproj" />
    <ProjectReference Include="..\FurnitureGardenDesign.Web.ViewModels\FurnitureGardenDesign.Web.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Admin\Interfaces\Account\" />
    <Folder Include="Admin\Interfaces\Catalog\" />
    <Folder Include="Admin\Interfaces\Interactions\" />
    <Folder Include="Admin\Interfaces\Message\" />
    <Folder Include="Manager\Implementations\Account\" />
    <Folder Include="Manager\Implementations\Message\" />
    <Folder Include="Manager\Interfaces\Account\" />
    <Folder Include="Manager\Interfaces\Catalog\" />
    <Folder Include="Manager\Interfaces\Interactions\" />
    <Folder Include="Manager\Interfaces\Message\" />
  </ItemGroup>

</Project>
